package requester

import (
	commonProto "github.com/Grivn/phalanx/common/types/protos"
	"github.com/Grivn/phalanx/external"
)

type requesterImpl struct {
	// n indicates the total node amount in current cluster
	n int

	// author is the current node's identifier
	author uint64

	// sequence is the counter for the requests generated by current node
	sequence uint64

	// recorder is used to record all the requests in cluster, the key word is the identifier of these replicas
	recorder map[uint64]*requestPool

	// sender is used to send consensus message into cluster network
	sender *senderProxy

	// logger is used to print logs
	logger external.Logger
}

func newRequesterImpl(n int, author uint64, bidC chan *commonProto.BatchId, network external.Network, logger external.Logger) *requesterImpl {
	logger.Noticef("replica %d init request manager, cluster amount %d", author, n)
	rps := make(map[uint64]*requestPool)

	for i:=0; i<n; i++ {
		id := uint64(i+1)
		rp := newRequestPool(author, id, bidC, logger)
		rps[id] = rp
	}

	return &requesterImpl{
		n:        n,
		author:   author,
		recorder: rps,
		sender:   newSenderProxy(author, network),
		logger:   logger,
	}
}

func (r *requesterImpl) start() {
	for _, pool := range r.recorder {
		pool.start()
	}
}

func (r *requesterImpl) stop() {
	for _, pool := range r.recorder {
		pool.stop()
	}
}

func (r *requesterImpl) generate(bid *commonProto.BatchId) {
	if bid == nil {
		r.logger.Warningf("[%d Warning] received a nil batch id", r.author)
		return
	}

	r.sequence++
	msg := &commonProto.OrderedMsg{
		Type:     commonProto.OrderType_REQ,
		Author:   r.author,
		Sequence: r.sequence,
		BatchId:  bid,
	}

	r.logger.Infof("[%d Generate] ordered req for seq %d batch %s", r.author, r.sequence, bid.BatchHash)
	r.sender.broadcast(msg)
	r.record(msg)
}

func (r *requesterImpl) record(msg *commonProto.OrderedMsg) {
	r.recorder[msg.Author].record(msg)
}
