package requester

import (
	commonProto "github.com/Grivn/phalanx/common/protos"
	commonTypes "github.com/Grivn/phalanx/common/types"
	"github.com/Grivn/phalanx/external"
)

type requesterImpl struct {
	// n indicates the total node amount in current cluster
	n int

	// author is the current node's identifier
	author uint64

	// sequence is the counter for the requests generated by current node
	sequence uint64

	// recorder is used to record all the requests in cluster, the key word is the identifier of these replicas
	recorder map[uint64]*requestPool

	// sender is used to send consensus message into cluster network
	sender external.Network

	// logger is used to print logs
	logger external.Logger
}

func newRequesterImpl(n int, author uint64, sendC commonTypes.RequesterSendChan, network external.Network, logger external.Logger) *requesterImpl {
	logger.Noticef("replica %d init request manager, cluster amount %d", author, n)
	rps := make(map[uint64]*requestPool)

	for i:=0; i<n; i++ {
		id := uint64(i+1)
		rp := newRequestPool(author, id, sendC, logger)
		rps[id] = rp
	}

	return &requesterImpl{
		n:        n,
		author:   author,
		recorder: rps,
		sender:   network,
		logger:   logger,
	}
}

func (r *requesterImpl) start() {
	for _, pool := range r.recorder {
		pool.start()
	}
}

func (r *requesterImpl) stop() {
	for _, pool := range r.recorder {
		pool.stop()
	}
}

// propose is used to generate a proposal with the tx-batch send from tx-pool
func (r *requesterImpl) propose(batch *commonProto.TxBatch) {
	if batch == nil {
		r.logger.Warningf("[%d Warning] received a nil batch id", r.author)
		return
	}

	r.sequence++
	proposal := &commonProto.Proposal{
		Author:   r.author,
		Sequence: r.sequence,
		TxBatch:  batch,
	}

	r.logger.Infof("[%d Generate] ordered req for seq %d batch %s", r.author, r.sequence, batch.Digest)
	r.sender.BroadcastProposal(proposal)
	r.receiveProposal(proposal)
}

func (r *requesterImpl) receiveProposal(proposal *commonProto.Proposal) {
	r.recorder[proposal.Author].record(proposal)
}
