# Sample consensus configuration file

# Protocol options
protocol:
  # Number of replicas (servers)
  "n": 3

  # Fault tolerance (max number of faulty replicas)
  "f": 1

  # Checkpoint period
  checkpointPeriod: 10

  # Max log size (high minus low water mark)
  logsize: 20

  # Timeouts
  timeout:
    # Request processing timeout (triggers view change)
    request: 2s

    # Prepare processing timeout (forwards request if expired)
    prepare: 1s

    # Initial view change timeout (triggers another view change)
    viewchange: 3s

# List of peers (IDs and network addresses)
peers:
    - id: 0
      addr: ":8000"
    - id: 1
      addr: ":8001"
    - id: 2
      addr: ":8002"
